# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "eb10468d10054d15f2b6f8946cd46797779aa20a7617ceb4be884189f219bc9a164e56a5b9f7bec392a804ff3740210348d73db77a37adb542a8e08d429ac92700"
genesis_address_str = "23p53TdHiiF9dsUQGnS7HhjbScRxyjmjUXg"
blockchain_pubkey_str = "03fa74a5559c336d2a5901525a6c35d98d503bd9eb786a61186b9b616878cf927f"
blockchain_seckey_str = "c3cdf67a11558ebcebb7f98dee7496c7b8f544432f810cbb472ed473515d8e87"
genesis_timestamp = 1541117729
# genesis_coin_volume = 100e12
default_connections = [
]
peer_list_url = ""
#port = 6000
#web_interface_port = 6420

[visor]
#max_coin_supply = 1e8
#distribution_addresses_total = 100
#initial_unlocked_count = 25
#unlock_addresss_rate = 5
#unlocked_time_internal = 60 * 60 * 24 * 365
#max_droplet_precision = 3
#default_max_block_size = 32 * 1024
distribution_addresses = [
"2C8moj8UmNcJRSruKB7HZwBjSToYXortSDo",
"o5Rf5zeTJ7bgzkQ4367SVgu342R5S6pKJ5",
"fzaCZDB8XXaoxBQ5VUpPiHfRPJPy5uthqu",
"2R6RrG6fkGoCBM8DvHRnbgB5k2DU2sPfjVX",
"QWejMvjvRb7wS8KBmP5XyX5umZTkaneKWp",
"VGgZgQRgf9M4xeXeZym2o3iFE2WVfeVhWq",
"2MN3bisp57a4QhDG9ESu5Chs6ZuSpi1KDUS",
"qqcsr43fz9717Dtpsf5j7m6EzC9mMSRiy5",
"267xzCnnj2GQYLFK2Qb5FxT3nyWropXNXBa",
"RJmhQps75PhC4fjvG492vrCGxzeY1V3WUT",
"25YTrZjmk4M5XRM8ZeXUwWnBb7AdQk2BJbf",
"dRMaWRd6UsFou1UATaJvPzBvqN8nCK1ZTy",
"mJyxHLzjLviJHas4fz6ZQqrmLzLyMWrv7i",
"4UAHUyRtcvRexDFQ6om9N3ZnD5NkgZaJ9k",
"21TeNDPCjh5XyfTriuNzgGxbE9tuUqPGA4e",
"26TC4Rf4ECSFUdMqLdh2E7tcKFzjV9DjnLp",
"39RGALcQDtgLB8SLTwCwFEQQPNA6kApndJ",
"u9bSCdXD7bkrPztpnuzDbosvLPmJudGAKU",
"2PA58WunafLcj1YVbucfZKXG14Ssf8PMRwP",
"2ateNuuTaZSx4um6QxfBJmvAqrwNf15C3qY",
"2PRikJ1roG91agqDVw3Xdu5nKRTaNsQLwnC",
"sjbb2VsAWw1xVqHeAAoQrRdhZ9Y8Zx5GeP",
"Ht8JDE1yG3xycr1SZTFRqgdcEnDfpMZ5Hm",
"2Yf6qk5CLyCheLBSQxXu5AWMTbtBVKcrRnm",
"2caFMbgxj1QNMVt5p4eH9XFLkJrGNx8f91j",
"7XcPoumMqJ2K6wqJCT4RG9ArDA3aszhfUw",
"QvvHC1ijeenkrmvGTT5yL4nfnaN9oWuHre",
"oGXeCwYNmCn9qHhTtYzaAQUb1ZS6xipAJZ",
"2ibTjh1Ed5AGMZzpTbhtkAxdqXEUmDbqiHe",
"uKhFRP4M3gYczya36dPSyy8fHKhJRVQAzG",
"SFC9BPggFYbNdzALQmZBUDNZ8L67wANvQ7",
"4kDn6FwG3tS4DjFdrKrksnwgsRuCYRu2Z8",
"2UyURaDwkGn9Gh2mgPmsb949QEZrXEER6G3",
"ySNAFStWQTb5ZwB9LYmcU8h6hyNSTdS1iQ",
"2ML21LsZrcJPkeDYD8L5WPmQeNeuRQWXCAh",
"2aLmdGKgJk6NiSCoQbsx2HU6du9UjxHMrSa",
"suWJFJGqPM5YAcnqa8k7XmBEsCX4Y2shyz",
"FNr2aPkz6owCxUmeRi9ohw2aRwNAGe7R3N",
"29UiVK8C1HyiocwjSgQQpB4RSdgFhVBPmEx",
"LK813jjSoPByJ2HzaJnVmAseKWdW755uHX",
"2k1WuDe1RC9nXZeAUHynTAsaTRsR4t7Eexf",
"pS24g9zJ2CmMbwe7gXsGd4yurnCZSdgM4V",
"2i3ToePt3jrLxmU69MUvznT6vYPvYDmsXTE",
"2YqLRahy9rCYfLmMtWieJFresKww8WtRq58",
"2WpWXnU4xjYHeyUPuc1pis2Nb1qqZJs7vuN",
"2mTvv3S6UdFE4m816jgc5qpfXfTYwbAQv1y",
"2BbQE7GQ44dFB3fkvgRgJkn8Vq1uJdgPPRN",
"Sk1jqXLbug35XxfZPGht1KsDcq3NW5Uegv",
"FhPiYhF9RtpbJiq5JJScrj6pRSwNiNuWtx",
"7yrmXXVzaSveuMsh5o3WoWSrp9ezVTbqc1",
"2VjK2wcTNypN17h6MX2YYWVttXDemHw6bMf",
"2XQPD9Hj2koPHwxYHbGBufByu4uxxzoYexT",
"chwS3Uf5amemAvaK6Y8Ky3H8gmLttBsKCi",
"2Q9r2MLrD8EEQBotdYtxdgavcZXy6AZ1WWq",
"4uNXmqGiRvfTswt3a1pHP49DEYWCcgovZB",
"HpVWHNX5M5MNSwmbgNFjuxw5dyWnpNB8Tt",
"tBb1gw5V2ekjdExYFnjeafDi99Xeh41Vtb",
"2Uct6hqVtVrm5BNmgUwmgqTVFah9i9o27HR",
"2PvAaFpa4FbT1uNgVXhCAfESMJ1H6QDwBSr",
"1Hv9H8ywNj9wFgqAHwT4sMefLKDF9796kW",
"2WzW8tXaRg5j5ety4T9SRmBqDi7xz5zpB1p",
"26JAjJ1EmPbzMePWcLEtveprAwjpZnYMeVR",
"riezonbg5LGo4Kopyo6CLBsyxmhsGGiFnX",
"2cMgv3xSUU6tKC5VZai8jUBW5RD4Z9uinZC",
"Fp5u72TjsWKHxWL8uX7nYSVUbgMVn1BLBJ",
"XvtXBBNSWJgaCNkXicMfsXq2YeWRPzmxxp",
"Gkc9EvyvhvHn1aBh7iBhUpvv76X6PY8mj7",
"2i2yDPrTXSbquf2HPx8Jbu3gcjFS7KjRccL",
"wyU2hbNHC2hvrzzKRAtpHT8yf3Jdva746o",
"2Sh6r8URsJS8nMquQ3gKfVzcbiGsvgNibyF",
"23rmAHhZBPddnsTWWUA9hCqNjVFT5NXcq5q",
"2AsTbA1iiz8eTeQujyMYJJXXz3epQuedkCx",
"2REkRteLYULS3SwsXP43pEUF4Q1zHsmyPyo",
"hS9Ng36UxRfCv8tvpwrZtAPejiYtghUzqC",
"2mokZP7BXuU44zkB5Vh6ThXdTYE4cznAgeH",
"2keNLGdDhFtoRJ54AvCcbpT2cXWzaDWVc6i",
"ReTKfnH752kEykE6xs1CxofykspcCYwABj",
"peGnVk3ZDwTNs3XmPu1XqcNSFZt99hKFrh",
"iQu1k8KPQbyFAG83jQaiiorweF6HmUNNPn",
"xr3PBJGF4u5JhvEkccJZoQXb4pXardE7QB",
"XZfwqRrVACSoQCr6NLcJbaBFqXwWqYiwSj",
"4ap82kJYu2oz4FQAzD6H9FnHt9sL4oGn87",
"2RKgp3M56YRzcNaLA91RUJaeuy7VhaxTJBC",
"ayToJ5vGc1ckG4BczRDsV1FaQEXiouqBc2",
"HHWG1HEZR7DXstNir9VjkKbpjz4kACxPrE",
"2JafZAkqhBWr42yGgZFoM38wRXTYbPSxQPo",
"H2dbVRtkaLVC9hzNZXQHomG5k5ixWH7Coc",
"2TiyMRwDzjRSvNuMyqYgiLkJjLGzEXrcX3W",
"2Kt8uWPdxxXvE18Jhic2LZ1iWqJAacKVMTY",
"cSthuXCL2iMg84Kj7euJzR4Aoow24tdH7a",
"nARvMm7pixSoYH3VQRY9RMDX88Jywfk1Qw",
"ZxfJPGVEFZavHcXrfch8R9PRUtfeSHtFNu",
"oN7ccZHPcVCRaVQH1Sfqn111TbV599pJL9",
"8bXe5a6KpkLxjvaPgtKVingC524dA7ABwE",
"tyewjDtMvb7FrrpWQGG9KTj7KhBeCmX3MN",
"2X7PH9d1e1iKWuJBYCG9SjwUpGfyQasUNuK",
"2itibpAsQCRz6FNnNsSwFGvASsyN9LLCVWQ",
"NfmR9yxQ278DEFtRJA59LMpbHPKwhesi6d",
"Ez6Dp8c636eS2B5S2mBDbSbBn7Yey4tGgj",
"2T32wc6bC5pKAuMuXNyVU4ABLPJbf9WUt7G"
]
